//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP320_Kolpakov.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logins
    {
        public int ID { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<int> EmpID { get; set; }
    
        public virtual Employe Employe { get; set; }
    }
}
